/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package examenproblema1;

/**
 *
 * @author Mario Pineda
 */
public class PruebaPanel extends javax.swing.JPanel {

  /**
   * Creates new form PruebaPanel
   */
  public PruebaPanel() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jTextField3 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jCheckBox1 = new javax.swing.JCheckBox();
    jLabel6 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jCheckBox2 = new javax.swing.JCheckBox();
    jPanel2 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
    setLayout(new java.awt.BorderLayout(0, 10));

    jPanel1.setLayout(new java.awt.GridLayout(7, 2, 20, 20));

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Modelo:");
    jPanel1.add(jLabel2);
    jPanel1.add(jTextField1);

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Color:");
    jPanel1.add(jLabel3);
    jPanel1.add(jTextField2);

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Matrícula:");
    jPanel1.add(jLabel4);
    jPanel1.add(jTextField3);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Cobertura Amplia:");
    jPanel1.add(jLabel5);

    jCheckBox1.setText("Daños a Terceros");
    jPanel1.add(jCheckBox1);

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText("Año de Fabircación:");
    jPanel1.add(jLabel6);
    jPanel1.add(jTextField4);

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Tipo de Coche");
    jPanel1.add(jLabel7);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Familiar", "Item 2", "Item 3", "Item 4" }));
    jPanel1.add(jComboBox1);

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel8.setText("Tipo de Pintura:");
    jPanel1.add(jLabel8);

    jCheckBox2.setText("Metalizada");
    jPanel1.add(jCheckBox2);

    add(jPanel1, java.awt.BorderLayout.CENTER);

    jButton1.setText("Aceptar");
    jPanel2.add(jButton1);

    jButton2.setText("Cancelar");
    jPanel2.add(jButton2);

    add(jPanel2, java.awt.BorderLayout.SOUTH);

    jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    jLabel1.setText("Datos del auto");
    jLabel1.setToolTipText("");
    jPanel3.add(jLabel1);

    add(jPanel3, java.awt.BorderLayout.NORTH);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables
}
