/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tareacalculadora;

/**
 *
 * @author Mario Pineda
 */
public class PanelCalculadora extends javax.swing.JPanel {

  /**
   * Creates new form PanelCalculadora
   */
  public PanelCalculadora() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    areaCalculos = new javax.swing.JTextField();
    panelCentro = new javax.swing.JPanel();
    botonSiete = new javax.swing.JButton();
    botonOcho = new javax.swing.JButton();
    botonNueve = new javax.swing.JButton();
    botonDivision = new javax.swing.JButton();
    botonCuatro = new javax.swing.JButton();
    botonCinco = new javax.swing.JButton();
    botonSeis = new javax.swing.JButton();
    botonMultiplicar = new javax.swing.JButton();
    botonUno = new javax.swing.JButton();
    botonDos = new javax.swing.JButton();
    botonTres = new javax.swing.JButton();
    botonRestar = new javax.swing.JButton();
    botonCero = new javax.swing.JButton();
    botonDecimal = new javax.swing.JButton();
    botonIgual = new javax.swing.JButton();
    botonSumar = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    panelNorte.setLayout(new java.awt.GridLayout());
    panelNorte.add(areaCalculos);

    add(panelNorte, java.awt.BorderLayout.NORTH);

    panelCentro.setLayout(new java.awt.GridLayout(4, 4));

    botonSiete.setText("7");
    panelCentro.add(botonSiete);

    botonOcho.setText("8");
    panelCentro.add(botonOcho);

    botonNueve.setText("9");
    panelCentro.add(botonNueve);

    botonDivision.setText("/");
    panelCentro.add(botonDivision);

    botonCuatro.setText("4");
    panelCentro.add(botonCuatro);

    botonCinco.setText("5");
    panelCentro.add(botonCinco);

    botonSeis.setText("6");
    panelCentro.add(botonSeis);

    botonMultiplicar.setText("*");
    panelCentro.add(botonMultiplicar);

    botonUno.setText("1");
    panelCentro.add(botonUno);

    botonDos.setText("2");
    panelCentro.add(botonDos);

    botonTres.setText("3");
    panelCentro.add(botonTres);

    botonRestar.setText("-");
    panelCentro.add(botonRestar);

    botonCero.setText("0");
    panelCentro.add(botonCero);

    botonDecimal.setText(".");
    panelCentro.add(botonDecimal);

    botonIgual.setText("=");
    panelCentro.add(botonIgual);

    botonSumar.setText("+");
    panelCentro.add(botonSumar);

    add(panelCentro, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField areaCalculos;
  private javax.swing.JButton botonCero;
  private javax.swing.JButton botonCinco;
  private javax.swing.JButton botonCuatro;
  private javax.swing.JButton botonDecimal;
  private javax.swing.JButton botonDivision;
  private javax.swing.JButton botonDos;
  private javax.swing.JButton botonIgual;
  private javax.swing.JButton botonMultiplicar;
  private javax.swing.JButton botonNueve;
  private javax.swing.JButton botonOcho;
  private javax.swing.JButton botonRestar;
  private javax.swing.JButton botonSeis;
  private javax.swing.JButton botonSiete;
  private javax.swing.JButton botonSumar;
  private javax.swing.JButton botonTres;
  private javax.swing.JButton botonUno;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  // End of variables declaration//GEN-END:variables
}
