/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tarea;

/**
 *
 * @author Mario Pineda
 */
public class PanelContenedor extends javax.swing.JPanel {

  /**
   * Creates new form PanelContenedor
   */
  public PanelContenedor() {
    initComponents();
    
  }

  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelWest = new javax.swing.JPanel();
    botonSnap = new javax.swing.JCheckBox();
    labelX = new javax.swing.JLabel();
    areaTextoX = new javax.swing.JTextField();
    botonGrid = new javax.swing.JCheckBox();
    labelY = new javax.swing.JLabel();
    areaTextoY = new javax.swing.JTextField();
    panelEst = new javax.swing.JPanel();
    botonOk = new javax.swing.JButton();
    botonCancelar = new javax.swing.JButton();
    botonHelp = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 30));
    setLayout(new java.awt.BorderLayout(10, 10));

    panelWest.setName(""); // NOI18N
    panelWest.setOpaque(false);
    panelWest.setLayout(new java.awt.GridLayout(2, 3, 20, 10));

    botonSnap.setText("Snap to Grid");
    botonSnap.setToolTipText("");
    botonSnap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    botonSnap.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonSnapActionPerformed(evt);
      }
    });
    panelWest.add(botonSnap);

    labelX.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelX.setLabelFor(panelEst);
    labelX.setText("X:");
    labelX.setMaximumSize(new java.awt.Dimension(3, 16));
    labelX.setPreferredSize(new java.awt.Dimension(5, 5));
    panelWest.add(labelX);
    labelX.getAccessibleContext().setAccessibleDescription("");

    areaTextoX.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    areaTextoX.setText("8");
    areaTextoX.setToolTipText("8");
    panelWest.add(areaTextoX);

    botonGrid.setText("Show Grid");
    panelWest.add(botonGrid);

    labelY.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelY.setText("Y:");
    labelY.setMaximumSize(new java.awt.Dimension(3, 16));
    labelY.setMinimumSize(new java.awt.Dimension(1, 16));
    labelY.setPreferredSize(new java.awt.Dimension(1, 5));
    panelWest.add(labelY);

    areaTextoY.setText("8");
    panelWest.add(areaTextoY);

    add(panelWest, java.awt.BorderLayout.CENTER);

    panelEst.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

    botonOk.setText("Ok");
    botonOk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonOkActionPerformed(evt);
      }
    });
    panelEst.add(botonOk);

    botonCancelar.setText("Cancel");
    panelEst.add(botonCancelar);

    botonHelp.setText("Help");
    panelEst.add(botonHelp);

    add(panelEst, java.awt.BorderLayout.EAST);
  }// </editor-fold>//GEN-END:initComponents

  private void botonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonOkActionPerformed

  private void botonSnapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSnapActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonSnapActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField areaTextoX;
  private javax.swing.JTextField areaTextoY;
  private javax.swing.JButton botonCancelar;
  private javax.swing.JCheckBox botonGrid;
  private javax.swing.JButton botonHelp;
  private javax.swing.JButton botonOk;
  private javax.swing.JCheckBox botonSnap;
  private javax.swing.JLabel labelX;
  private javax.swing.JLabel labelY;
  private javax.swing.JPanel panelEst;
  private javax.swing.JPanel panelWest;
  // End of variables declaration//GEN-END:variables
}
