/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tareaprinter;

/**
 *
 * @author Mario Pineda
 */
public class PanelPrinter extends javax.swing.JPanel {

  /**
   * Creates new form PanelPrinter
   */
  public PanelPrinter() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCentro = new javax.swing.JPanel();
    panelNorte = new javax.swing.JPanel();
    textPrinter = new javax.swing.JLabel();
    panelCentroDos = new javax.swing.JPanel();
    campoIzquiero = new javax.swing.JTextField();
    panelCentroIzquierdo = new javax.swing.JPanel();
    checkImagen = new javax.swing.JCheckBox();
    checkText = new javax.swing.JCheckBox();
    checkCode = new javax.swing.JCheckBox();
    campoCentro = new javax.swing.JTextField();
    panelCentroDerecho = new javax.swing.JPanel();
    botonSelection = new javax.swing.JRadioButton();
    botonAll = new javax.swing.JRadioButton();
    botonApplet = new javax.swing.JRadioButton();
    campoDerecho = new javax.swing.JTextField();
    panelSur = new javax.swing.JPanel();
    textPrint = new javax.swing.JLabel();
    boxImpresion = new javax.swing.JComboBox<>();
    checkImprimir = new javax.swing.JCheckBox();
    panelEste = new javax.swing.JPanel();
    botonOk = new javax.swing.JButton();
    botonCancelar = new javax.swing.JButton();
    botonSetup = new javax.swing.JButton();
    botonHelp = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 10));
    setLayout(new java.awt.BorderLayout());

    panelCentro.setLayout(new java.awt.BorderLayout());

    panelNorte.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    textPrinter.setText("Printer: MyPrinter");
    panelNorte.add(textPrinter);

    panelCentro.add(panelNorte, java.awt.BorderLayout.NORTH);

    panelCentroDos.setLayout(new java.awt.GridLayout(1, 5));
    panelCentroDos.add(campoIzquiero);

    panelCentroIzquierdo.setLayout(new java.awt.GridLayout(3, 1));

    checkImagen.setText("Image");
    panelCentroIzquierdo.add(checkImagen);

    checkText.setText("Text");
    panelCentroIzquierdo.add(checkText);

    checkCode.setText("Code");
    panelCentroIzquierdo.add(checkCode);

    panelCentroDos.add(panelCentroIzquierdo);
    panelCentroDos.add(campoCentro);

    panelCentroDerecho.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

    botonSelection.setText("Selection");
    panelCentroDerecho.add(botonSelection);

    botonAll.setText("All");
    panelCentroDerecho.add(botonAll);

    botonApplet.setText("Applet");
    panelCentroDerecho.add(botonApplet);

    panelCentroDos.add(panelCentroDerecho);
    panelCentroDos.add(campoDerecho);

    panelCentro.add(panelCentroDos, java.awt.BorderLayout.CENTER);

    panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

    textPrint.setText("Print Quality:");
    panelSur.add(textPrint);

    boxImpresion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HIGH", "MEDIUM", "LOW" }));
    panelSur.add(boxImpresion);

    checkImprimir.setText("Print to File");
    panelSur.add(checkImprimir);

    panelCentro.add(panelSur, java.awt.BorderLayout.SOUTH);

    add(panelCentro, java.awt.BorderLayout.CENTER);

    panelEste.setLayout(new java.awt.GridLayout(4, 1, 2, 5));

    botonOk.setText("Ok");
    panelEste.add(botonOk);

    botonCancelar.setText("Cancel");
    panelEste.add(botonCancelar);

    botonSetup.setText("Setup...");
    panelEste.add(botonSetup);

    botonHelp.setText("Help");
    panelEste.add(botonHelp);

    add(panelEste, java.awt.BorderLayout.EAST);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton botonAll;
  private javax.swing.JRadioButton botonApplet;
  private javax.swing.JButton botonCancelar;
  private javax.swing.JButton botonHelp;
  private javax.swing.JButton botonOk;
  private javax.swing.JRadioButton botonSelection;
  private javax.swing.JButton botonSetup;
  private javax.swing.JComboBox<String> boxImpresion;
  private javax.swing.JTextField campoCentro;
  private javax.swing.JTextField campoDerecho;
  private javax.swing.JTextField campoIzquiero;
  private javax.swing.JCheckBox checkCode;
  private javax.swing.JCheckBox checkImagen;
  private javax.swing.JCheckBox checkImprimir;
  private javax.swing.JCheckBox checkText;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelCentroDerecho;
  private javax.swing.JPanel panelCentroDos;
  private javax.swing.JPanel panelCentroIzquierdo;
  private javax.swing.JPanel panelEste;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  private javax.swing.JLabel textPrint;
  private javax.swing.JLabel textPrinter;
  // End of variables declaration//GEN-END:variables
}
