/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package graficapastelbarras;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mario Pineda
 */
public class DialogoAyuda extends javax.swing.JDialog {

  private String titulo;

  /**
   * Creates new form DialogoBarras
   */
  public DialogoAyuda(java.awt.Frame parent, boolean modal, String titulo) {
    super(parent, modal);
    this.titulo = titulo;
    initComponents();
    this.setDialogo(titulo);
  }

  public void setDialogo(String titulo) {
    if (titulo == "ayuBarra") {
      try {
        this.setTitle("Ayuda de la grafica de Barras");
        panelAyuda.setPage(getClass().getResource("/archivos/AcercaDeBarras.html"));
      } catch (IOException ex) {
        System.out.println("No se puede" + ex);
      }
    } else {
      try {
        this.setTitle("Ayuda de la grafica de Pastel");
        panelAyuda.setPage(getClass().getResource("/archivos/AcercaDePastel.html"));
      } catch (IOException ex) {
        System.out.println("No se puede" + ex);
      }
    }
    panelCentro.setViewportView(panelAyuda);
    this.getContentPane().add(panelCentro);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelSur = new javax.swing.JPanel();
    botonAceptar = new javax.swing.JButton();
    panelCentro = new javax.swing.JScrollPane();
    panelAyuda = new javax.swing.JEditorPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    botonAceptar.setText("Aceptar");
    botonAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonAceptarActionPerformed(evt);
      }
    });
    panelSur.add(botonAceptar);

    getContentPane().add(panelSur, java.awt.BorderLayout.PAGE_END);

    panelCentro.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    panelCentro.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

    panelAyuda.setEditable(false);
    panelAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    panelCentro.setViewportView(panelAyuda);

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
    this.setVisible(false); //Ocultamos la ventana cuando de aceptar
  }//GEN-LAST:event_botonAceptarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAceptar;
  private javax.swing.JEditorPane panelAyuda;
  private javax.swing.JScrollPane panelCentro;
  private javax.swing.JPanel panelSur;
  // End of variables declaration//GEN-END:variables
}
