/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelesconherencia;

/**
 *
 * @author Mario Pineda
 */
public class PanelNieto extends PanelHijo {

  /**
   * Creates new form PanelNieto
   */
  public PanelNieto() {
    //Lo mismo que el panel Hijo
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    botonNieto = new javax.swing.JButton();

    botonNieto.setBackground(new java.awt.Color(206, 17, 38));
    botonNieto.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    botonNieto.setText("c..!");
    add(botonNieto);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonNieto;
  // End of variables declaration//GEN-END:variables
}
