package oyenteinternoanonimo;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author Mario Pineda
 */
public class Ventana extends javax.swing.JFrame {

  /**
   * Creates new form Ventana
   */
  public Ventana() {
    initComponents();
    //Creamos una nueva Tab del tipo JPanel
    //Y se añaden clases ANONIMAS
    panelCentro.addTab("Jpanel", new JPanel()); //Creacion de Objeto Anonimo 
    panelCentro.addTab("Background", new JPanel() { //Con las {} crea una clase interna sin nombre pero q hereda de JPanel
      {//ESte es el "constructor" pq no tiene nombre
        setBackground(Color.CYAN); //Colocamos el color del fondo
      }

    }
    )/*Este parentesis señala el final del objeto*/; //Creacion de Objeto Anonimo
    panelCentro.addTab("Elipse", new JPanel() {
      {
        setBackground(Color.WHITE);
      }

      @Override
      public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int ancho = this.getWidth();
        int alto = this.getHeight();
        g.fillOval(0, 0, ancho, alto);
      }
    });
    panelCentro.addTab("Cruz", new JPanel() {
      {
        setBackground(Color.BLACK);
      }
      @Override
      public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.WHITE);
        g.drawLine(0, 0, this.getWidth(), this.getHeight());
        g.drawLine(0, this.getHeight(), this.getWidth(), 0);
      }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCentro = new javax.swing.JTabbedPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Oyentes Internos");

    panelCentro.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane panelCentro;
  // End of variables declaration//GEN-END:variables
}
