/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e201separadorbilletes;

import javax.swing.JTextField;

/**
 *
 * @author Mario Pineda
 */
public class VentanaMonedas extends javax.swing.JFrame {

  /**
   * Creates new form VentanaMonedas
   */
  public VentanaMonedas() {
    initComponents();
  }

  public void addEventos(OyenteVentana e) {
    this.areaCantidad.addActionListener(e);
  }

  public JTextField[] getCampos() {
    return new JTextField[]{cambio1, cambio2, cambio5, cambio10, cambio20, cambio50, cambio100, cambio200, cambio500};
  }

  public JTextField getCampoCantidad() {
    return areaCantidad;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    etiquetaCantidad = new javax.swing.JLabel();
    areaCantidad = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    cambio500 = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    cambio10 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    cambio200 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    cambio5 = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    cambio100 = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    cambio2 = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    cambio50 = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    cambio1 = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    cambio20 = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    etiquetaCantidad.setText("Cantidad:");
    jPanel2.add(etiquetaCantidad);

    areaCantidad.setColumns(10);
    jPanel2.add(areaCantidad);

    getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

    jPanel1.setLayout(new java.awt.GridLayout(6, 5, 10, 10));

    jLabel1.setText("Denominacion");
    jPanel1.add(jLabel1);

    jLabel2.setText("Cantidad");
    jPanel1.add(jLabel2);

    jLabel3.setText("Denominacion");
    jPanel1.add(jLabel3);

    jLabel4.setText("Cantidad");
    jPanel1.add(jLabel4);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("500");
    jPanel1.add(jLabel5);
    jPanel1.add(cambio500);

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("10");
    jPanel1.add(jLabel7);
    jPanel1.add(cambio10);

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("200");
    jPanel1.add(jLabel6);
    jPanel1.add(cambio200);

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("5");
    jPanel1.add(jLabel8);
    jPanel1.add(cambio5);

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel9.setText("100");
    jPanel1.add(jLabel9);
    jPanel1.add(cambio100);

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel10.setText("2");
    jPanel1.add(jLabel10);
    jPanel1.add(cambio2);

    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel11.setText("50");
    jPanel1.add(jLabel11);
    jPanel1.add(cambio50);

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setText("1");
    jPanel1.add(jLabel12);
    jPanel1.add(cambio1);

    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel13.setText("20");
    jPanel1.add(jLabel13);
    jPanel1.add(cambio20);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField areaCantidad;
  private javax.swing.JTextField cambio1;
  private javax.swing.JTextField cambio10;
  private javax.swing.JTextField cambio100;
  private javax.swing.JTextField cambio2;
  private javax.swing.JTextField cambio20;
  private javax.swing.JTextField cambio200;
  private javax.swing.JTextField cambio5;
  private javax.swing.JTextField cambio50;
  private javax.swing.JTextField cambio500;
  private javax.swing.JLabel etiquetaCantidad;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
