/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package controljugadores;

import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Mario Pineda
 */
public class DialogoRegistroJugador extends javax.swing.JDialog {

  /**
   * Creates new form DialogoRegistroJugador
   */
  //Lo de modal se refiere a si bloqueará la ventana de debajo
  public DialogoRegistroJugador(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.setSize(400, 300);//Definimos el tamaño de la ventana
  }
  
  public JButton getBotonAceptar() {
    return this.botonAceptar;
  }
  
  //Añadimos los eventos para los MENU ITEMS
  public void addEventos(OyenteJugadores oyente) {
    this.botonAceptar.addActionListener(oyente);
    this.botonCancelar.addActionListener(oyente);
    this.addWindowListener(oyente);
    
    //le ponemos nombre a cada cosa q genera eventos y a la venana misma
    this.botonAceptar.setName("aceptar");
    this.botonCancelar.setName("cancelar");
    this.setName("dialogo");
  }
  
  public void show(String titutlo,
    String textoBoton,
    boolean estadoNombre,
    boolean estadoCombos) {

    //Modificamos el titulo de la ventana
    this.setTitle(titutlo);
    //Modificamos el texto del boton aceptar para que cambie cuando l necesitemos
    this.botonAceptar.setText(textoBoton);
    //Activamos o desactivamos el campo a 
    this.campoNombre.setEnabled(estadoNombre);
    //Actvamos o desactivamos las opciones editables
    this.comboPronostico.setEnabled(estadoCombos);
    this.comboTemperatura.setEnabled(estadoCombos);
    this.comboHumedad.setEnabled(estadoCombos);
    this.comboViento.setEnabled(estadoCombos);
    this.comboJugar.setEnabled(estadoCombos);
    //Preguntamos por el padre de la ventana
    JFrame padre = (JFrame) this.getParent();
    //Obtenemos las coordenadas del centro de la ventana utilizando la
    //Posicion del padre, la longitud a la mitad menos la midad de las
    //Longitudes de las ventanas de dialogo
    int x = padre.getX() + (padre.getWidth() / 2) - (this.getWidth() / 2);
    int y = padre.getY() + (padre.getHeight() / 2) - (this.getHeight() / 2);
    this.setLocation(x, y);
    
    this.setVisible(true);
  }
  
  public void setComponentes(String[] valores) {
    this.campoNombre.setText(valores[0]);
    this.comboPronostico.setSelectedItem(valores[1]);
    this.comboTemperatura.setSelectedItem(valores[2]);
    this.comboHumedad.setSelectedItem(valores[3]);
    this.comboViento.setSelectedItem(valores[4]);
    this.comboJugar.setSelectedItem(valores[5]);
  }
  
  public String[] getComponentes() {
    return new String[]{
      this.campoNombre.getText(),
      (String) this.comboPronostico.getSelectedItem(),
      (String) this.comboTemperatura.getSelectedItem(),
      (String) this.comboHumedad.getSelectedItem(),
      (String) this.comboViento.getSelectedItem(),
      (String) this.comboJugar.getSelectedItem()
    };
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    etiquetaNombre = new javax.swing.JLabel();
    campoNombre = new javax.swing.JTextField();
    panelCentro = new javax.swing.JPanel();
    etiquetaPronostico = new javax.swing.JLabel();
    comboPronostico = new javax.swing.JComboBox<>();
    etiquetaTemperatura = new javax.swing.JLabel();
    comboTemperatura = new javax.swing.JComboBox<>();
    etiquetaHumedad = new javax.swing.JLabel();
    comboHumedad = new javax.swing.JComboBox<>();
    etiquetaViento = new javax.swing.JLabel();
    comboViento = new javax.swing.JComboBox<>();
    etiquetaJugar = new javax.swing.JLabel();
    comboJugar = new javax.swing.JComboBox<>();
    panelSur = new javax.swing.JPanel();
    botonAceptar = new javax.swing.JButton();
    botonCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Jugador");

    panelNorte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos del Jugador:"));

    etiquetaNombre.setText("Nomber del Jugador:");
    panelNorte.add(etiquetaNombre);

    campoNombre.setColumns(25);
    panelNorte.add(campoNombre);

    getContentPane().add(panelNorte, java.awt.BorderLayout.NORTH);

    panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Estado del Tiempo:"));
    panelCentro.setLayout(new java.awt.GridLayout(5, 2));

    etiquetaPronostico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaPronostico.setText("Pronostico:");
    panelCentro.add(etiquetaPronostico);

    comboPronostico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soleado", "Nublado", "Lluvioso" }));
    panelCentro.add(comboPronostico);

    etiquetaTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaTemperatura.setText("Temperatura:");
    panelCentro.add(etiquetaTemperatura);

    comboTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calor", "Templado", "Frío" }));
    panelCentro.add(comboTemperatura);

    etiquetaHumedad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaHumedad.setText("Humedad:");
    panelCentro.add(etiquetaHumedad);

    comboHumedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Normal", "Baja" }));
    panelCentro.add(comboHumedad);

    etiquetaViento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaViento.setText("Viento:");
    panelCentro.add(etiquetaViento);

    comboViento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
    panelCentro.add(comboViento);

    etiquetaJugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    etiquetaJugar.setText("¿Jugará?:");
    panelCentro.add(etiquetaJugar);

    comboJugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
    panelCentro.add(comboJugar);

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    botonAceptar.setText("Aceptar");
    panelSur.add(botonAceptar);

    botonCancelar.setText("Cancelar");
    panelSur.add(botonCancelar);

    getContentPane().add(panelSur, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonAceptar;
  private javax.swing.JButton botonCancelar;
  private javax.swing.JTextField campoNombre;
  private javax.swing.JComboBox<String> comboHumedad;
  private javax.swing.JComboBox<String> comboJugar;
  private javax.swing.JComboBox<String> comboPronostico;
  private javax.swing.JComboBox<String> comboTemperatura;
  private javax.swing.JComboBox<String> comboViento;
  private javax.swing.JLabel etiquetaHumedad;
  private javax.swing.JLabel etiquetaJugar;
  private javax.swing.JLabel etiquetaNombre;
  private javax.swing.JLabel etiquetaPronostico;
  private javax.swing.JLabel etiquetaTemperatura;
  private javax.swing.JLabel etiquetaViento;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  // End of variables declaration//GEN-END:variables
}
