package contextografico;

/**
 *
 * @author Mario Pineda
 */
public class PanelContextoGrafico extends javax.swing.JPanel {

  /**
   * Creates new form PanelContextoGrafico
   */
  public PanelContextoGrafico() {
    initComponents();
    panelCentro.addTab("Letras", new PanelLetras());
    panelCentro.addTab("Polígonos", new PanelPoligonos());
    panelCentro.addTab("Arcos", new PanelArcos());
    panelCentro.addTab("Lineas", new PanelPrimitivas());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCentro = new javax.swing.JTabbedPane();

    setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
    setLayout(new java.awt.BorderLayout());
    add(panelCentro, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane panelCentro;
  // End of variables declaration//GEN-END:variables
}
