/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author Mario Pineda
 */
public class PanelConversor extends javax.swing.JPanel {

  /**
   * Creates new form panelConversor
   */
  public PanelConversor() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    etiquetaTexto = new javax.swing.JLabel();
    panelCentro = new javax.swing.JPanel();

    setLayout(new java.awt.BorderLayout());

    etiquetaTexto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    etiquetaTexto.setText("CONVERSOR DE TEMPERATURA");
    etiquetaTexto.setToolTipText("");
    panelNorte.add(etiquetaTexto);

    add(panelNorte, java.awt.BorderLayout.PAGE_START);

    javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
    panelCentro.setLayout(panelCentroLayout);
    panelCentroLayout.setHorizontalGroup(
      panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 443, Short.MAX_VALUE)
    );
    panelCentroLayout.setVerticalGroup(
      panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 269, Short.MAX_VALUE)
    );

    add(panelCentro, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel etiquetaTexto;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  // End of variables declaration//GEN-END:variables
}
