/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package n102random;

import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Mario Pineda
 */
public final class PanelRandom extends javax.swing.JPanel {

  int[] arr = {0, 1, 2, 3, 4, 5, 6, 7, 8};

  /**
   * Creates new form PanelRandom
   */
  public PanelRandom() {
    initComponents();
    generarBotones();
  }

  public void generarBotones() {
    ArrayList<Integer> dat = new ArrayList<>();

    for (int i = 0; i < arr.length; i++) {
      dat.add(arr[i]);
    }
    setBotones(dat);
  }

  public JButton[] getBotones() {
    return new JButton[]{boton1, boton2, boton3, boton4, boton5, boton6, boton7, boton8, boton9};
  }

  public void setBotones(ArrayList<Integer> datos) {
    ArrayList<Integer> aux = new ArrayList<>();
    int i = 0;
    while(i < arr.length) {
      int dato = (int) (Math.random() * 9);
      if (!aux.contains(dato)) {
        getBotones()[i].setText("" + datos.get(arr[dato]));
        aux.add(dato);
        i++;
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    boton1 = new javax.swing.JButton();
    boton2 = new javax.swing.JButton();
    boton3 = new javax.swing.JButton();
    boton4 = new javax.swing.JButton();
    boton5 = new javax.swing.JButton();
    boton6 = new javax.swing.JButton();
    boton7 = new javax.swing.JButton();
    boton8 = new javax.swing.JButton();
    boton9 = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    jButton1.setText("Nueva Partida");
    jPanel1.add(jButton1);

    add(jPanel1, java.awt.BorderLayout.PAGE_START);

    jPanel2.setLayout(new java.awt.GridLayout(3, 3));

    boton1.setText("jButton2");
    jPanel2.add(boton1);

    boton2.setText("jButton2");
    jPanel2.add(boton2);

    boton3.setText("jButton2");
    jPanel2.add(boton3);

    boton4.setText("jButton2");
    jPanel2.add(boton4);

    boton5.setText("jButton2");
    jPanel2.add(boton5);

    boton6.setText("jButton2");
    jPanel2.add(boton6);

    boton7.setText("jButton2");
    jPanel2.add(boton7);

    boton8.setText("jButton2");
    jPanel2.add(boton8);

    boton9.setText("jButton2");
    jPanel2.add(boton9);

    add(jPanel2, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton boton1;
  private javax.swing.JButton boton2;
  private javax.swing.JButton boton3;
  private javax.swing.JButton boton4;
  private javax.swing.JButton boton5;
  private javax.swing.JButton boton6;
  private javax.swing.JButton boton7;
  private javax.swing.JButton boton8;
  private javax.swing.JButton boton9;
  private javax.swing.JButton jButton1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables
}
