/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tareacolor;

/**
 *
 * @author Mario Pineda
 */
public class PanelSeleccion extends javax.swing.JPanel {

  /**
   * Creates new form PanelSeleccion
   */
  public PanelSeleccion() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelNorte = new javax.swing.JPanel();
    boxColores = new javax.swing.JComboBox<>();
    panelCentro = new javax.swing.JPanel();
    opcionBackground = new javax.swing.JCheckBox();
    opcionForeground = new javax.swing.JCheckBox();
    panelSur = new javax.swing.JPanel();
    botonOk = new javax.swing.JToggleButton();
    botonCancelar = new javax.swing.JToggleButton();

    setLayout(new java.awt.BorderLayout());

    panelNorte.setLayout(new java.awt.GridLayout());

    boxColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "GREEN", "BLUE", "CYAN" }));
    panelNorte.add(boxColores);

    add(panelNorte, java.awt.BorderLayout.NORTH);

    panelCentro.setPreferredSize(new java.awt.Dimension(100, 10));

    opcionBackground.setText("Background");
    opcionBackground.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    panelCentro.add(opcionBackground);

    opcionForeground.setText("Foreground");
    opcionForeground.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    panelCentro.add(opcionForeground);

    add(panelCentro, java.awt.BorderLayout.CENTER);

    botonOk.setText("Ok");
    panelSur.add(botonOk);

    botonCancelar.setText("Cancelar");
    panelSur.add(botonCancelar);

    add(panelSur, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton botonCancelar;
  private javax.swing.JToggleButton botonOk;
  private javax.swing.JComboBox<String> boxColores;
  private javax.swing.JCheckBox opcionBackground;
  private javax.swing.JCheckBox opcionForeground;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelNorte;
  private javax.swing.JPanel panelSur;
  // End of variables declaration//GEN-END:variables
}
