/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;
import modelos.Fuerzas;

/**
 *
 * @author Mario Pineda
 */
public class FrameEquilibrio extends javax.swing.JFrame {

  private Fuerzas fuerza;

  /**
   * Creates new form FrameEquilibrio
   */
  public FrameEquilibrio(Fuerzas fuerza) {
    this.fuerza = fuerza;
    initComponents();
  }

  public void addEventos(ActionListener e) {
    this.opcionAbrir.addActionListener(e);
    this.opcionSalir.addActionListener(e);

    this.opcionAbrir.setName("abrir");
    this.opcionSalir.setName("salir");
  }
  
  public Fuerzas getFuerza(){
    return fuerza;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCentro = new PanelFuerzas(fuerza);
    barraMenu = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    opcionAbrir = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    opcionSalir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout panelCentroLayout = new javax.swing.GroupLayout(panelCentro);
    panelCentro.setLayout(panelCentroLayout);
    panelCentroLayout.setHorizontalGroup(
      panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    panelCentroLayout.setVerticalGroup(
      panelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 280, Short.MAX_VALUE)
    );

    getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

    menuArchivo.setText("Archivo");

    opcionAbrir.setText("Abrir Archivo");
    menuArchivo.add(opcionAbrir);
    menuArchivo.add(jSeparator1);

    opcionSalir.setText("Salir Del Programa");
    menuArchivo.add(opcionSalir);

    barraMenu.add(menuArchivo);

    setJMenuBar(barraMenu);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barraMenu;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenuItem opcionAbrir;
  private javax.swing.JMenuItem opcionSalir;
  private javax.swing.JPanel panelCentro;
  // End of variables declaration//GEN-END:variables
}
