/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author Mario Pineda
 */
public class PanelGrafica extends javax.swing.JPanel {

  /**
   * Creates new form PanelGrafica
   */
  public PanelGrafica() {
    initComponents();
  }
  
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    graficaCalculos1 = new modelos.GraficaCalculos();

    setLayout(new java.awt.BorderLayout());

    javax.swing.GroupLayout graficaCalculos1Layout = new javax.swing.GroupLayout(graficaCalculos1);
    graficaCalculos1.setLayout(graficaCalculos1Layout);
    graficaCalculos1Layout.setHorizontalGroup(
      graficaCalculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    graficaCalculos1Layout.setVerticalGroup(
      graficaCalculos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    add(graficaCalculos1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private modelos.GraficaCalculos graficaCalculos1;
  // End of variables declaration//GEN-END:variables
}
