/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Mario Pineda
 */
public class PanelGrafica extends javax.swing.JPanel {

  private int segmentos;
  private double[] datos;
  private double suma;

  /**
   * Creates new form PanelGrafica
   */
  public PanelGrafica() {
    initComponents();
  }

  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    int ancho = this.getWidth();
    int alto = this.getHeight();
    int radio = Math.min(ancho / 2, alto / 2);
    g.translate(ancho / 2, alto / 2);
    int anguloInicial = 0;

    for (int i = 0; i < datos.length; i++) {
      int rojo = (int) (Math.random() * 256);
      int verde = (int) (Math.random() * 256);
      int azul = (int) (Math.random() * 256);
      Color colorRandom = new Color(rojo, verde, azul);//Nuevo color
      g.setColor(colorRandom);
      int angulos = (int) ((360 * datos[i]) / suma); //Obtenemos los segmentos en los q vamos a dividir la grafica
      g.fillArc(0, 0, radio * 2, radio * 2, anguloInicial, angulos * i);
      anguloInicial = angulos * i;
    }
    g.setColor(Color.red);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
