/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author mario
 */
public class PanelTrianguloInscrito extends javax.swing.JPanel {

  /**
   * Creates new form PanelTrianguloInscrito
   */
  public PanelTrianguloInscrito() {
    initComponents();
  }

  public void addEventos(ActionListener e){
    botonAumentar.addActionListener(e);
    botonDisminuir.addActionListener(e);
    
    botonAumentar.setName("aumentar");
    botonDisminuir.setName("disminuir");
  }
  
  public void setNuevoRadio(int radio){
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelSur = new javax.swing.JPanel();
    botonAumentar = new javax.swing.JToggleButton();
    botonDisminuir = new javax.swing.JToggleButton();
    triCirDibujable1 = new trianguloinscritocirculo.TriCirDibujable();

    setLayout(new java.awt.BorderLayout());

    botonAumentar.setText("Aumentar");
    panelSur.add(botonAumentar);

    botonDisminuir.setText("Disminuir");
    panelSur.add(botonDisminuir);

    add(panelSur, java.awt.BorderLayout.SOUTH);

    javax.swing.GroupLayout triCirDibujable1Layout = new javax.swing.GroupLayout(triCirDibujable1);
    triCirDibujable1.setLayout(triCirDibujable1Layout);
    triCirDibujable1Layout.setHorizontalGroup(
      triCirDibujable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 1515, Short.MAX_VALUE)
    );
    triCirDibujable1Layout.setVerticalGroup(
      triCirDibujable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 841, Short.MAX_VALUE)
    );

    add(triCirDibujable1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton botonAumentar;
  private javax.swing.JToggleButton botonDisminuir;
  private javax.swing.JPanel panelSur;
  private trianguloinscritocirculo.TriCirDibujable triCirDibujable1;
  // End of variables declaration//GEN-END:variables
}
