/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import javax.swing.event.ChangeListener;

/**
 *
 * @author Mario Pineda
 */
public class PanelCirculoSlider extends javax.swing.JPanel {

  /**
   * Creates new form PanelCirculoSlider
   */
  public PanelCirculoSlider() {
    initComponents();
  }

  public void addEventos(ChangeListener e) {
    this.slideRadio.addChangeListener(e);
  }

  public void setEtiquetaRadio(String textoRadio) {
    etiquetaRadio.setText(textoRadio);
  }

  public void setEtiquetaDiametro(String textoDiametro) {
    etiquetaDiametro.setText(textoDiametro);
  }

  public void setEtiquetaArea(String textoArea) {
    etiquetaArea.setText(textoArea);
  }

  public void setEtiquetaCircunferencia(String textoCircunferencia) {
    etiquetaCircunferencia.setText(textoCircunferencia);
  }

  public void setRadio(int radio) {
    circuloTarea1.setRadio(radio);
  }

  public int getValorSlider() {
    return slideRadio.getValue();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelSur = new javax.swing.JPanel();
    etiquetaRadio = new javax.swing.JLabel();
    etiquetaArea = new javax.swing.JLabel();
    etiquetaDiametro = new javax.swing.JLabel();
    etiquetaCircunferencia = new javax.swing.JLabel();
    circuloTarea1 = new vistas.CirculoTarea();
    slideRadio = new javax.swing.JSlider();

    setLayout(new java.awt.BorderLayout());

    panelSur.setBackground(circuloTarea1.getBackground());
    panelSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 1));

    etiquetaRadio.setText("Radio: ");
    panelSur.add(etiquetaRadio);

    etiquetaArea.setText("Area: ");
    panelSur.add(etiquetaArea);

    etiquetaDiametro.setText("Diametro: ");
    panelSur.add(etiquetaDiametro);

    etiquetaCircunferencia.setText("Circunferencia: ");
    panelSur.add(etiquetaCircunferencia);

    add(panelSur, java.awt.BorderLayout.PAGE_END);

    javax.swing.GroupLayout circuloTarea1Layout = new javax.swing.GroupLayout(circuloTarea1);
    circuloTarea1.setLayout(circuloTarea1Layout);
    circuloTarea1Layout.setHorizontalGroup(
      circuloTarea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 439, Short.MAX_VALUE)
    );
    circuloTarea1Layout.setVerticalGroup(
      circuloTarea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 282, Short.MAX_VALUE)
    );

    add(circuloTarea1, java.awt.BorderLayout.CENTER);

    slideRadio.setBackground(circuloTarea1.getBackground());
    slideRadio.setMajorTickSpacing(5);
    slideRadio.setMaximum(200);
    slideRadio.setMinimum(100);
    slideRadio.setMinorTickSpacing(5);
    slideRadio.setOrientation(javax.swing.JSlider.VERTICAL);
    slideRadio.setPaintLabels(true);
    slideRadio.setPaintTicks(true);
    slideRadio.setToolTipText("5");
    slideRadio.setValue(150);
    add(slideRadio, java.awt.BorderLayout.EAST);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private vistas.CirculoTarea circuloTarea1;
  private javax.swing.JLabel etiquetaArea;
  private javax.swing.JLabel etiquetaCircunferencia;
  private javax.swing.JLabel etiquetaDiametro;
  private javax.swing.JLabel etiquetaRadio;
  private javax.swing.JPanel panelSur;
  private javax.swing.JSlider slideRadio;
  // End of variables declaration//GEN-END:variables
}
