package vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author Mario Pineda
 */
public class PanelConversor extends javax.swing.JPanel {

  /**
   * Creates new form panelConversor
   */
  public PanelConversor() {
    initComponents();
  }

  public void addEventos(ActionListener e) {
    botonCelcius.addActionListener(e);
    botonFarenjei.addActionListener(e);
    botonKelvin.addActionListener(e);
    botonKelvinCelcius.addActionListener(e);

    botonCelcius.setName("cf");
    botonFarenjei.setName("fc");
    botonKelvin.setName("ck");
    botonKelvinCelcius.setName("kc");
  }

  public void setAreaGrados(String cantGrados) {
    areaGrados.setText(cantGrados);
  }

  public void setGradosEntrada(String textoEntrada) {
    etiquetaGradoEntrada.setText(textoEntrada);
  }

  public void setGradosEquivale(String textoEquivale) {
    etiquetaEquivale.setText(textoEquivale);
  }

  public void setGradosConversion(String textoConversion) {
    etiquetaConversion.setText(textoConversion);
  }

  public String getAreaGrados() {
    return areaGrados.getText();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    etiquetaTexto = new javax.swing.JLabel();
    panelCentro = new javax.swing.JPanel();
    panelSuperior = new javax.swing.JPanel();
    etiquetaGrados = new javax.swing.JLabel();
    areaGrados = new javax.swing.JTextField();
    panelIzquierdo = new javax.swing.JPanel();
    botonCelcius = new javax.swing.JButton();
    botonFarenjei = new javax.swing.JButton();
    botonKelvin = new javax.swing.JButton();
    botonKelvinCelcius = new javax.swing.JButton();
    panelDerecho = new javax.swing.JPanel();
    etiquetaGradoEntrada = new javax.swing.JLabel();
    etiquetaEquivale = new javax.swing.JLabel();
    etiquetaConversion = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 20));
    setLayout(new java.awt.BorderLayout());

    etiquetaTexto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
    etiquetaTexto.setText("CONVERSOR DE TEMPERATURA");
    etiquetaTexto.setToolTipText("");
    add(etiquetaTexto, java.awt.BorderLayout.NORTH);

    panelCentro.setLayout(new java.awt.BorderLayout(10, 10));

    etiquetaGrados.setText("Grados:");
    panelSuperior.add(etiquetaGrados);

    areaGrados.setColumns(5);
    panelSuperior.add(areaGrados);

    panelCentro.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

    panelIzquierdo.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

    botonCelcius.setText("ºF a ºC");
    panelIzquierdo.add(botonCelcius);

    botonFarenjei.setText("ºC a ºF");
    panelIzquierdo.add(botonFarenjei);

    botonKelvin.setText("ºC a K");
    panelIzquierdo.add(botonKelvin);

    botonKelvinCelcius.setText("K a ºC");
    panelIzquierdo.add(botonKelvinCelcius);

    panelCentro.add(panelIzquierdo, java.awt.BorderLayout.LINE_START);

    panelDerecho.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

    etiquetaGradoEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaGradoEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    panelDerecho.add(etiquetaGradoEntrada);

    etiquetaEquivale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaEquivale.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    panelDerecho.add(etiquetaEquivale);

    etiquetaConversion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    etiquetaConversion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    panelDerecho.add(etiquetaConversion);

    panelCentro.add(panelDerecho, java.awt.BorderLayout.CENTER);

    add(panelCentro, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField areaGrados;
  private javax.swing.JButton botonCelcius;
  private javax.swing.JButton botonFarenjei;
  private javax.swing.JButton botonKelvin;
  private javax.swing.JButton botonKelvinCelcius;
  private javax.swing.JLabel etiquetaConversion;
  private javax.swing.JLabel etiquetaEquivale;
  private javax.swing.JLabel etiquetaGradoEntrada;
  private javax.swing.JLabel etiquetaGrados;
  private javax.swing.JLabel etiquetaTexto;
  private javax.swing.JPanel panelCentro;
  private javax.swing.JPanel panelDerecho;
  private javax.swing.JPanel panelIzquierdo;
  private javax.swing.JPanel panelSuperior;
  // End of variables declaration//GEN-END:variables
}
