/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contadorclics;

import java.awt.event.MouseListener;
import java.awt.event.MouseWheelListener;

/**
 *
 * @author Mario Pineda
 */
public class PanelContador extends javax.swing.JPanel {

  /**
   * Creates new form PanelContador
   */
  public PanelContador() {
    initComponents();
  }
  
  public void setEtiqueta(int cant) {
    this.etiquetaContador.setText(Integer.toString(cant));
  }
  
  public void addEventos(MouseWheelListener e) {
    //this.addMouseListener(e);
    this.addMouseWheelListener(e);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    etiquetaContador = new javax.swing.JLabel();

    setLayout(new java.awt.GridLayout(1, 1));

    etiquetaContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    add(etiquetaContador);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel etiquetaContador;
  // End of variables declaration//GEN-END:variables
}
